### ISSUE TITLE
Failed to add secret. Name is invalid.

### ISSUE THREAD

**Issue by oxr463** [fnkr/github-action-ghr#5] opened 2020-03-24 13:08 UTC
Cannot name secret `GITHUB_TOKEN`, or else it gives me the following warning,

>  Failed to add secret. Name is invalid.

**Comment by oxr463** [comment] 2020-03-24 13:30
I fixed it by renaming the secret as follows:

`GITHUB_TOKEN: ${{ secrets.GHR_TOKEN }}`

**Comment by fnkr** [comment] 2020-03-24 20:41
Duplicate of #6.

**Closed as completed by fnkr** 2020-03-24 20:41 UTC
